services:
  ratings:
    build: "../ratings/"
    image: ghcr.io/drd4n/bookinfo-ratings:dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME
  reviews:
    build: .
    image: ghcr.io/drd4n/bookinfo-reviews:dev
    ports:
      - "8082:9080"
    environment:
      RATINGS_HOSTNAME:  http://ratings:8080